Homework 1
naloevaOlya/iosSchool pull request #1
Opened 2023-03-17 08:27 UTC by naloevaOlya

fisrt home work done

2023-03-17 09:03 UTC, naloevaOlya commented
first homework done

2023-03-18 12:02 UTC, vaganova-ann requested changes

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +func checkData(attack: Int, protection: Int, health: Int, damage: [Int])throws {
нужен пробел между скобкой и throws

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            throw GameErrors.invalidData
Вариант с ошибкой хороший, но хочу еще один инициализатор, который вместо ошибки возвращает nil, и, соответственно, пример обработки этого nil во вью контроллере

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +    enum Level: Double {
Мне кажется, что два enum это избыточно, тем более, если тип Double у Level нигде не учитывается

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            switch self.level {
вместо switch можно сразу взять rawValue от level и отдавать ее в функцию recovery?

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            throw GameErrors.protectionNil
То есть, если у монстра нет защиты, то игрок совсем никак не может его ударить?

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +    let cubes = Cubes(cubes: [monster.attackModifier(defensive: gamer.protection, attack: monster.attack)])
Мне кажется, здесь должно учитываться, кто на кого нападает, почему мы всегда берем защиту от игрока, а атаку от монстра?

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/ViewController.swift
> +            var gamer = try Gamer(attack: 17, protection: 6, health: 25,
При сокращении длины строки каждый параметр нужно расположить на отдельной строчке

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +    init(attack: Int, protection: Int, health: Int, damage: [Int], level: Level) throws {
Здесь тоже хочу еще один иницализатор, который может возвращать nil

2023-03-18 12:02 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +func gamerAttacks(gamer: Gamer, monster: inout Monster)throws {
нужен пробел между скобкой и throws

2023-03-19 11:01 UTC, closed without merging