Homework 11
naloevaOlya/iosSchool pull request #12
Opened 2023-04-30 21:11 UTC by naloevaOlya

При регистрации есть проверка на совпадение паролей, добавлен лоадер.
    вопрос: что нужно делать при успешной регистрации пользователя? На какой экран переходить и тд

При авторизации также проходит запрос профиля, сохраняется его username в Userdefaults. Во вью модель ячейки подтягиваются данные пользователя из UserDefaults. 
При загрузке экрана локаций сохраняется дата, которая также пробрасывается в итоге во вью модель профиля

2023-05-01 05:21 UTC, vaganova-ann requested changes
При успешной регистрации выполняем те же действия, что и при успешной авторизации - сохраняем токен, переходим на таббар

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Auth/AuthDataProvider.swift
> +
пустая строчка лишняя

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +                self?.dataProvider.getProfile(profileId: token.userId) { result in
потеряла weak self
можно вызов dataProvider.getProfile(profileId: token.userId) вынести в отдельную функцию вью контроллера, тогда не будет путаницы с  weak self и визуально будет чище

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Location/LocationAssembly.swift
> +        .init(storageManager: StorageManagerImp(), dataProvider: locationDataProvider())
разве у нас нет в Assembly экземпляра storageManager и мы его сюда передаем, а не создаем новый?

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Location/LocationViewController.swift
> +        storageManager.saveAppLaunchDate()
мне кажется, сохранение даты последнего входа нужно сделать в AppCoordinator, вдруг потом в TabBarController добавится новый таб, который будет первым в списке табов

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Profile/ProfileAssembly.swift
> +        ), storageManager: StorageManagerImp())
используй storageManager из Assembly

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +    init(data: ProfileCellsData, storageManager: StorageManager) {
думаю здесь можно не передавать data откуда-то снаружи, давай будем ее создавать и хранить только в пределах этого вью контроллера

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationViewController.swift
> +        guard isPasswordsEqual(password: password, repeatPassword: repeatPassword) == true else {
здесь можно == true убрать, будет работать просто 
guard isPasswordsEqual(password: password, repeatPassword: repeatPassword) else

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Services/StorageManager.swift
> +        return formatter.string(from: Date.init())
можно просто Date()

2023-05-01 05:21 UTC, vaganova-ann commented on iosSchool/Services/StorageManager.swift
> +        return UserDefaults.standard.string(forKey: StorageManagerKey.username.rawValue) ?? "Login"
лучше сделать ?? "", чтобы переиспользовать метод getUserName
а в профайл вью контроллере уже помнять пустую дату и пустой логин на нужные плейсхолдеры
У меня сейчас после регистрации и входа в приложение не отобразился логин в профиле, надо поправить

2023-05-01 22:14 UTC, naloevaOlya commented
Все правки внесены. 
успешная регистрация -> экран локаций (тут же сохранение имени пользователя в UserDefaults) -> в профиле корректно отображается имя пользователя (тестила не раз)
кнопка "выйти" из профиля -> удаляем токен и данные пользователя -> экран авторизации
При повторном входе сразу экран локаций -> сохранение имени пользователя -> отображается в профиле

2023-05-02 02:49 UTC, vaganova-ann requested changes

2023-05-02 02:49 UTC, vaganova-ann commented on iosSchool/Location/LocationViewController.swift
> +        self.getProfile(userld: token?.userId ?? "")
если у нас userId == nil то может не надо профиль запрашивать? я бы сделала 
private func getProfile(userld: String?) {
и тут первой строчкой гард
}

2023-05-02 02:49 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +        let data = self.setData()
self не обязательно

2023-05-02 02:49 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +        return ProfileCellsData(
return не обязательно

2023-05-02 02:49 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +            userName: storageManager.getUserName() == "" ? nil : storageManager.getUserName(),
свифт линт не просит поменять == "" на .isEmpty?

2023-05-02 02:49 UTC, vaganova-ann commented on iosSchool/AppCoordinator.swift
> +        assembly.storageManager.saveUserName(username: assembly.storageManager.getToken()?.userId ?? "")
а здесь зачем? постоянно будет пересохраняться один и тот же username

2023-05-02 06:15 UTC, naloevaOlya commented on iosSchool/Profile/ProfileViewController.swift
> +            userName: storageManager.getUserName() == "" ? nil : storageManager.getUserName(),
не просит, но поменяю, будет лучше выглядеть

2023-05-02 06:17 UTC, naloevaOlya commented on iosSchool/AppCoordinator.swift
> +        assembly.storageManager.saveUserName(username: assembly.storageManager.getToken()?.userId ?? "")
это с прошлого раза не убрала вроде

2023-05-02 11:42 UTC, vaganova-ann approved these changes

2023-05-02 11:43 UTC, merged