UIColorWell in profile
naloevaOlya/iosSchool pull request #13
Opened 2023-05-02 13:55 UTC by naloevaOlya

Добавлена иконка приложения
Добавлена обработка UIColorWell в профиле.
При первом запуске экран профиля заливается дефолтным цветом, при выборе цвета background профиля меняется на этот цвет, данные сохраняются в UserDefaults. При повторном входе background профиля соответствует последнему выбранному и сохраненному цвету.
Если выйти из профиля, то данные удаляются

2023-05-06 13:02 UTC, vaganova-ann requested changes

2023-05-06 13:02 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +                cell.setSetting(color: profileColor)
может мы цвет бекгрунда во вью модель занесем?

2023-05-06 13:02 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        tableView.reloadRows(at: index, with: .fade)
а tableView.reloadData() чем плох?

2023-05-06 13:02 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +protocol ProfileViewDelegate: AnyObject {
наверное этот протокол должен быть в ProfileView

2023-05-06 13:02 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +            color.addTarget(self, action: #selector(colorChange(_ :)), for: .valueChanged)
давай вынесем эту строку в функцию awakeFromNib
я не уверена, но может быть такое, что при каждом вызове update на колор велл будет вешаться таргет, снова и снова

2023-05-06 13:02 UTC, vaganova-ann commented on iosSchool/Services/StorageManager.swift
> +        return UIColor(red: CGFloat((components[0] as NSString).floatValue),
red на следующую строку, выровнять все остальные строки по red, последнюю скобку на следующую строку

2023-05-06 13:03 UTC, vaganova-ann commented
Выглядит круто)

2023-05-06 15:44 UTC, naloevaOlya commented
Все правки внесены. Обновление цвета ячеек теперь проходит корректнее.
Теперь в кружочке колор велл еще сохраняется выбранный цвет

2023-05-07 11:29 UTC, vaganova-ann requested changes
Сейчас только заметила, что при переходе в профиль в консоль сыпятся ошибки констрейнтов, надо поправить верстку

2023-05-10 02:30 UTC, vaganova-ann approved these changes

2023-05-10 02:55 UTC, merged