second homework is done
naloevaOlya/iosSchool pull request #3
Opened 2023-03-23 13:19 UTC by naloevaOlya

second homework is done

2023-03-24 03:25 UTC, vaganova-ann requested changes

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +        return self.attack - gamer.protection  + 1
Лишний пробел перед плюсом

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +        return self.attack - gamer.protection  + 1
если нет локальный переменных с таким же именем, то self не нужен
и return тоже не нужен в функции из одной строчки

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +        self.health -= damagePower
self не нужен

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +        return self.health > 0
return не нужен

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            gamer.gotHit(damagePower: self.getRandomValue(startOfRange: monster.damage[0],
если нам нужно перенести длинный вызов функции на несколько строчек, то делаем так
getRandomValue(
    startOfRange:
    endOfRange:
)
Если это вызов фунции в вызове функции, то переносим параметры какой то одной функции
self не нужен

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +    func attackModifier(gamer: Gamer, monster: Monster) -> Int {
в этом классе тоже надо почистить selfы

2023-03-24 03:25 UTC, vaganova-ann commented on iosSchool/ViewController.swift
> -        while isCreatureLive(health: gamer.health) && isCreatureLive(health: monster.health) {
переписать создание игрока и монстра через протокол
let player: Creature
player =

2023-03-24 16:30 UTC, naloevaOlya commented on iosSchool/FirstHomework.swift
> +        return self.attack - gamer.protection  + 1
сама функция теперь определена в extension Creature и вызываетсч не в цикле, а лишь раз для получения  неизменяемого значения

2023-03-27 03:06 UTC, vaganova-ann requested changes

2023-03-27 03:06 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +                endOfRange: monster.damage[1]))
закрывающие скобки должны быть на отдельной строчке

2023-03-27 03:06 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +                endOfRange: gamer.damage[1]))
закрывающие скобки должны быть на отдельной строчке

2023-03-27 03:06 UTC, vaganova-ann commented on iosSchool/ViewController.swift
> +        let _: Creature
Это что?) это зачем?

2023-03-27 03:06 UTC, vaganova-ann commented on iosSchool/ViewController.swift
>          guard var gamer = Gamer(attack: 17, protection: 6, health: 25, damage: [1, 6], level: .middle) else {
Повторяю:
переписать создание игрока и монстра через протокол
let player: Creature
player = Gamer(attack: 17, protection: 6, health: 25, damage: [1, 6], level: .middle)

2023-03-27 08:09 UTC, naloevaOlya commented on iosSchool/ViewController.swift
>          guard var gamer = Gamer(attack: 17, protection: 6, health: 25, damage: [1, 6], level: .middle) else {
итог, как по мне, немного костыльный. Пришлось выносить реализацию функции оздоровления у геймера, так как опять же объект соответствует протоколу, а хилиться может только геймер.

2023-03-29 03:13 UTC, vaganova-ann requested changes
Подписи к коммитам смешные) но лучше писать проще и по делу

2023-03-29 03:13 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            let cubes = Cubes(cubes: [attackModifier])
Отступы не по код стайлу

2023-03-29 03:13 UTC, vaganova-ann commented on iosSchool/FirstHomework.swift
> +            let cubes = Cubes(cubes: [attackModifier])
Отступы

2023-03-31 03:18 UTC, vaganova-ann approved these changes

2023-03-31 07:31 UTC, merged