the third homework is done. Registration screen filled with blue, app…
naloevaOlya/iosSchool pull request #4
Opened 2023-03-25 10:05 UTC by naloevaOlya

…ears after green Splash

2023-03-27 03:01 UTC, vaganova-ann requested changes

2023-03-27 03:01 UTC, vaganova-ann commented on iosSchool/Registration/RegAssembly.swift
> +//  RegAssembly.swift
Модуль должен называться Registration и все файлы этого модуля должны иметь не сокращенное название вначале файла.
Чтобы быстро переименовывать классы и названия их файлов по проекту, нажимаем двойным щелчком на название файла, выбираем Refactor -> Rename

2023-03-27 03:01 UTC, vaganova-ann commented on iosSchool/Registration/RegCoordinator.swift
> +
Пустая строка не нужна

2023-03-27 03:01 UTC, vaganova-ann commented on iosSchool/Registration/RegViewController.swift
> +
Пустая строка не нужна

2023-03-29 03:15 UTC, vaganova-ann requested changes

2023-03-29 03:15 UTC, vaganova-ann commented on iosSchool/SceneDelegate.swift
> +    func sceneWillEnterFoRegistrationround(_ scene: UIScene) {
А тут почему поменялось? Поправь обратно

2023-03-29 06:55 UTC, naloevaOlya commented on iosSchool/SceneDelegate.swift
> +    func sceneWillEnterFoRegistrationround(_ scene: UIScene) {
не поняла как так вышло, но все поправила

2023-03-31 03:19 UTC, vaganova-ann approved these changes

2023-03-31 07:35 UTC, merged