Homework 4
naloevaOlya/iosSchool pull request #5
Opened 2023-04-02 11:01 UTC by naloevaOlya

4 homework done.
1. The registration request is successful, the token is returned. Further, the request for authorization of the same user also passes successfully.
2. Implemented methods that request one location and a list of all locations, the desired model is returned
3.Implemented the "Character" model and the method that creates the request. It takes a character reference and returns the model we implemented

2023-04-04 03:11 UTC, vaganova-ann requested changes

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/APIClient/CharacterApiClient.swift
> +        onRequeestCompleted: @escaping (Result<Character, ApiError>) -> Void
опечатка в onRequeestCompleted

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/APIClient/LocationApiClient.swift
> +    onRequeestCompleted: @escaping (Result<LocationsList, ApiError>) -> Void
отступа не хватает

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/APIClient/LocationApiClient.swift
> +        onRequeestCompleted: @escaping (Result<Location, ApiError>) -> Void
опечатка бродит по всему коду

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/APIClient/RegistrationApiClient.swift
> +    func registration (
лишний пробел

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/AppCoordinator.swift
> +            // self?.startAuth()
комментарии в коде не нужны

2023-04-04 03:11 UTC, vaganova-ann commented on iosSchool/SceneDelegate.swift
> +    internal func sceneDidEnterBackground(_ scene: UIScene) {
зачем изменения в этом файле?

2023-04-05 11:13 UTC, naloevaOlya commented on iosSchool/SceneDelegate.swift
> +    internal func sceneDidEnterBackground(_ scene: UIScene) {
когда я меняла "reg"  на "registration" в прошлом ДЗ в этом файле функция "..foREGround" заменилась и я потом продолжала некорректно ее исправлять, сейчас поправила все как и должно быть

2023-04-05 11:14 UTC, naloevaOlya commented on iosSchool/APIClient/RegistrationApiClient.swift
> +    func registration (
были еще в нескольких местах, тоже поправила

2023-04-05 13:38 UTC, vaganova-ann approved these changes

2023-04-05 14:37 UTC, closed without merging