Homework 6
naloevaOlya/iosSchool pull request #7
Opened 2023-04-12 08:01 UTC by naloevaOlya

учтены правки с еще не аппрувнутого 5 ДЗ

2023-04-12 10:21 UTC, vaganova-ann requested changes
1) Не хватает констрейтов высоты у текстовых полей и кнопок, высота не по дизайну сейчас.
2) И давай еще через делегат текст филда будем переходить с текст филда на текст филд через кнопку return, а на последней кнопке закрывать клавиатуру
3) При нажатии на кнопки клавиатура тоже должна закрываться

2023-04-12 10:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +        selector: #selector(keyboardWillShow),
потеряла отступы здесь и на след строках

2023-04-12 10:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +
почему бы нам не сделать так же, как в авторизации: прокинуть логин, пароль и повторение пароля во вью контроллер и там выполнить запрос регистрации?

2023-04-12 10:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +
пробел не нужен, давай сделаем закрытие вью контроллера при нажатии на кнопку, нужно с вью контроллера прокинуть во вью кложуру, которую ты вызовешь здесь, а в кложуре во вью контроллере вызовем функцию self.dissmiss

2023-04-12 10:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationViewData.swift
> +        registrationTextFieldPlaceholder = ""
не, так нехорошо, по сути нам структура не нужна теперь, либо добавлять плейсхолдеры из кода, либо удалить здесь свойство и инициализатор

2023-04-12 10:21 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +        scrollView.keyboardDismissMode = .onDrag
Надо убрать, пусть экран скроллится при открытой клавиатуре и закрыватеся по тапу на экран

2023-04-16 14:30 UTC, vaganova-ann requested changes

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Auth/AuthCoordinator.swift
> +        controller.onOpenRegistration =  { [ weak controller ] in
пробелы после [ и перед ] не нужны

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Auth/AuthCoordinator.swift
> +            let coordinator = self.assembly.registrationCoordinator { [ self ] }
это что?

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationAssembly.swift
> +    func registrationCoordinator(onRegistrationSuccess: (() -> Void)?) -> RegistrationCoordinator
и вот тут я узнала, что у тебя не работает SwiftLint :) загляни в материалы первого занятия, настрой свифт линт и пофикси ворнинги этого модуля

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +
пустая строка не нужна

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationViewController.swift
> +        dataProvider.registration(username: login, password: password) { [ weak self ] result in
пробелы после [ и перед ] не нужны

2023-04-16 14:30 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationViewController.swift
> +        self.dismiss(animated: false)
почему false? пусть красиво закрывается

2023-04-17 10:08 UTC, naloevaOlya commented on iosSchool/Registration/RegistrationAssembly.swift
> +    func registrationCoordinator(onRegistrationSuccess: (() -> Void)?) -> RegistrationCoordinator
после подключения SwiftLint в этом модуле не появилось ни одного ворнинга. В других - да

2023-04-17 10:15 UTC, naloevaOlya commented on iosSchool/Auth/AuthCoordinator.swift
> +            let coordinator = self.assembly.registrationCoordinator { [ self ] }
нелепость

2023-04-19 01:58 UTC, vaganova-ann approved these changes

2023-04-24 11:28 UTC, merged