Homework 8
naloevaOlya/iosSchool pull request #9
Opened 2023-04-21 06:07 UTC by naloevaOlya

1. ячейки  таблицы с локациями соответствуют дизайну 
2. по кнопке рефреш в навбаре обновляются данные
3. экран профиля состоит из таблицы, которая состоит из трех ячеек. Вне таблицы есть кнопка "Выход" (очень хочу ее убрать, она бесполезна, учитывая наличие таббара. Но я оставила, так как нужно было по заданию)

P.S. Не понимаю, где корректно вызвать функцию update для третьей ячейки, чтобы оформить по дизайну текстфилды (

2023-04-23 07:04 UTC, vaganova-ann requested changes
1) В ячейке локации попробуй растянуть края ячейки в интерфейс билдере и посмотреть, на что он ругается
2) в ячейке с фото фотография, которая находится в бэкграунде, должна занимать всю ширину на любом девайся -> констрейнт ширины не нужен, может быть надо настроить content mode
3) в ячейке с фото для круглого фото top contstraint попробуй сделать относительно низа бэкграунд фото
4) вьюшки с датой регистрации и цветом профиля выглядит одинаково -> это должна быть одна ячейка с вью, которая содержит в себе лейбл слева и вью справа, ячейка используется 2 раза
5) вью, на которой лежит "дата регистрации" не может быть image view, добавляй обычную view, клади на нее лейбл и все остальное, все настраивай и верстай руками, аналогично для цвета профиля
6) запусти на 14 pro max, исправь недочеты

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/AppCoordinator.swift
> +        let profiLeVC = profileCoordinator.make()
Лишняя заглавная буква появилась

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Location/LocationViewController.swift
> +    @objc
давай пустую строку добавим после MARK

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileAssembly.swift
> +    func profileVC() -> ProfileViewController <ProfileViewImp>
пробел между ProfileViewController и <ProfileViewImp> не нужен здесь и ниже

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        backgroundColor = UIColor(named: "Lillac80")?.withAlphaComponent(1.06) ?? .white
разве альфа может быть больше 1?

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        table.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
по умолчанию инсеты 0, можно убрать эту строчку

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        let first = UINib(nibName: ProfileFirstCell.className, bundle: nil)
лучше firstCell и для остальных здесь тоже

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        table.topAnchor.constraint(equalTo: topAnchor, constant: -50).isActive = true
почему -50? мы, когда верстали экран авторизации и хотели, чтобы у нас картинка выходила за пределы safe area, верстали к superview, надо попробовать и здесь

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        button.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
близковато к нижнему краю, давай на 15 поднимем, чтобы получше смотрелось

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        table.bottomAnchor.constraint(greaterThanOrEqualTo: bottomAnchor, constant: -50).isActive = true
у тебя рядом два объекта, таблица и кнопка, и сейчас у таблицы два нижних констрейнта, один упирается в кнопку, один в нижнюю часть вью, того констрейнта, который к кнопке, будет достаточно, этот не нужен

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        button.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true    }
скобочка } заблудилась

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +class ProfileViewController <View: ProfileView>: BaseViewController<View> {
пробел между ProfileViewController и <View: не нужен

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileFirstCell.swift
> +    @IBOutlet private weak var profileImageView: UIImageView!
добавить вью модель ячейки и метод обновления фотографии

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileSecondCell.swift
> +    @IBOutlet private weak var label: UILabel!
добавить вью модель ячейки и метод обновления лейбла

2023-04-23 07:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +    @IBOutlet private weak var dateOfRegistartionLabel: UILabel!
Добавить вью модель ячейки и метод, обновляющий данные ячейки

2023-04-24 16:24 UTC, naloevaOlya commented on iosSchool/Profile/ProfileView.swift
> +        backgroundColor = UIColor(named: "Lillac80")?.withAlphaComponent(1.06) ?? .white
да может, он становится ярче и светлее, если увеличивать альфу дальше. Это значение подобрано эмпрически

2023-04-25 17:21 UTC, naloevaOlya commented on iosSchool/Profile/ProfileViewController.swift
> +class ProfileViewController <View: ProfileView>: BaseViewController<View> {
свифт линт ругается, если убрать пробел

2023-04-25 18:43 UTC, naloevaOlya commented
Исправления после ревью:
Верстка:
    1. в ячейке с фото настроен контент мод и круглое фото привязано к внешнему
    2. теперь в таблице 1 секция и 4 ячейки, но видов ячеек 3
    3.  последний вид ячеек настраивается на 99% кодом, в .xib файле только заливка цветом. Чтобы добиться разной высоты ячеек, я очень много эксперементировала, в итоге получилось сделать: констрейнт ширины задается в зависимости от ячейки, и далее закидывается вью, на которой лейбл слева и вьюха справа, в которой уже лежит либо лейбл с датой, либо UIColorWell. 
    // Но есть проблема, которую я не могу "избежать" при таком подходе: размер ячеек фиксированный и не подгоняется под размер устройства (альтернативные методы использования, например, стека с констрейнтами разной приоритетности и настройка  констрейнтов на самой вью, и разный приоритет для констрейнта ширины ячейки  - все провально)

Вьюмодели ячеек:
    не создала ProfileProvider , немного "вручную" обновляются данные в таблице, к тому же не ассинхронно (ой-ой). Сделала так поскольку, в 11 дз нужно будет сделать сбор данных с userDefault и тд для этого провайдера. В тестовом режим работает

2023-04-27 03:31 UTC, vaganova-ann requested changes

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +            cell.prepareForReuse()
а зачем? это функция вроде автоматически вызывается для ячеек, ее не надо руками дергать

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        if indexPath.row == 0 {
а че кстати, мож if заменить на switch?

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +            for: indexPath) as? ProfileFirstCell {
скобочку после indexPath надо на след строку перенести вместе с текстом за ней

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +         return 1
если 1 секция, то можно метод numberOfSections убрать, там по умолчанию 1

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        return UITableViewCell()
это зачем?

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +    private func setData(date: String, name: String, photo: UIImage?) {
как-то не очень с этой функцией, либо она должна создавать внутри себя новый объект типа ProfileCellsData и возвращать его, либо она вообще не нужна, тк дублирует логику инициализатора ProfileCellsData

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileFirstCell.swift
> +    override func prepareForReuse() {
а зачем этот метод в каждой ячейке?

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        profileData = data
когда данные приходят, надо вызвать обновление таблицы

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +        heightAnchor.constraint(equalToConstant: 123).isActive = true
надо в методах делегата таблицы поискать метод, в котором можно настраивать высоту ячейки, сейчас у тебя при каждом вызове tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) будет добавляться новый констрейнт

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +    private func setImage() {
а мы не можем не использовать ImageView и вместо нее настроить цвет, границы и закругление для cellView?

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +    func makeDateCell() {
все добавление констрейнтов нужно перенести в инициализацию ячейки, чтобы избежать их дублирования

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +        rightView.addSubview(dateLabel)
а если rightView сделать UIStackView, в  init положить туда и лейбл, и вью с цветом, и потом в апдейте один скрывать, другой показывать в зависимости от того, какую ячейку ты настраиваешь?

2023-04-27 03:31 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
>          table.delegate = self
надо настроить, чтобы при нажатии на ячейки они не подсвечивались

2023-04-27 07:47 UTC, naloevaOlya commented on iosSchool/Profile/ProfileView.swift
> +        return UITableViewCell()
это я хотела сделать функцию, котора принимала бы дженерик-класс и делала то, что делается в функции cellRowAt в каждом if/else. Уменьшить код в общем, но запамятовала о ней

2023-04-29 10:24 UTC, vaganova-ann requested changes
Про ProfileThirdCell:
1) Надо выбрать, верстаешь ты полностью кодом или полностью в интерфейс билдере. В зависимости от выбора, если только кодом, то не используй xib файл и @IBOutlet, если только в интерфейс билдере, то все констрейнты должны быть перенесены туда и многие настройки тоже
2) если верстка делается в коде, то констренйты должны создаваться в инициализаторе ячейки, чтобы мы могли гарантировать, что они создаются только один раз. подстановка вью модели будет происходить всякий раз при вызове метода tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) и соответственно у тебя каждый раз будут добавляться констрейнты, если оставить их в фукнции update

я предлагаю всю верстку перенести в интерфейс билдер, чтобы не путаться и не иметь лишних констрейнтов

2023-04-29 10:24 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
>          return UITableViewCell()
помоему на 131 строчке return уже лишний, попробуй его убрать

2023-04-29 10:24 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileFirstCell.swift
>              update(viewModel)
давай userLogoImageView тоже будет отображать фото пользователя как и profileImageView, у них разные плейсхолдеры, но фотка пользователя там одна и та же

2023-04-29 10:24 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +    @IBOutlet weak private var cellView: UIView!
у нас везде private weak var, здесь надо поправить

2023-04-29 10:24 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +        dateLabel.topAnchor.constraint(equalTo: rightView.topAnchor).isActive = true
никаких констрейтов мы не добавляем в стек вью, только кладем dateLabel и color в стек вью и настраиваем spacing и aligment с distribution

2023-04-29 11:02 UTC, naloevaOlya commented on iosSchool/Profile/ProfileView.swift
>          return UITableViewCell()
не лишний

2023-04-29 13:47 UTC, vaganova-ann requested changes

2023-04-29 13:47 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileFirstCell.swift
> +        let img  = viewModel.photo
пробел лишний

2023-04-29 13:47 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileFirstCell.swift
> +        let imgWithBorder = UIGraphicsImageRenderer(size: imgSize).image { _ in
давай занесем настройку изображения в инициализатор вью модели, тк вью модель отвечает за настройку данных для ячейки

по дизайну когда у нас плейсхолдер с  синим человечком в profileImageView, то в userLogoImageView плейсхолдер с белым человеком
а если пользователь устанавливает свое изображение, то оно отображается в обоих ImageView
надо попробовать настроить так

2023-04-29 13:47 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
> +        setLabel(label: dateLabel, labelText: viewModel.date ?? ".. .. ....")
настройки font и цвета текста я бы перенесла в инциализатор или функцию, которая будет вызываться для ячейки один раз, нет необходимости постоянно их дергать

2023-04-29 13:47 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
>              rightView.subviews[1].isHidden = true
ооочень сложно, у тебя же вынесены в код аутлеты dateLabel и  color, делай прям для них .isHidden = true

2023-04-29 13:47 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileThirdCell.swift
>      private func setCellView() {
содержимое этой функции тоже бы перенести в инциализатор или функцию, которая будет вызываться для ячейки один раз

2023-04-29 16:16 UTC, naloevaOlya commented
теперь инициализация вью модели профиля по дефолту со значениями во всех полях  = nil, и в самой ячейке уже ставится значение, если данные во вью модели nil
Поправила высоту последней ячейки, так как до этого расстрояние между ячейкой даты и профиля было = 21 (из-за добавления bottomAnchor в прошлый раз).

все настройки UI ячейки вынесла в .xib файл, только cellView.borderColor задается в функции setCellSetting
(инициализатор кастомный решила не прописывать, так как при таком подходе не учитывается UI .в xib, как я поняла. А настроить cellView.borderColor в интерфейс билдере не предоставляется возможным)

P.S. я поверю в Бога, когда ты аппрувнешь этот пулл реквест.

2023-04-30 03:51 UTC, vaganova-ann requested changes
Давай для полей photo userName и date в ProfileCellsData все их развороты опционала с помощью ?? занесем в инициализатор ProfileCellsData. Можно даже сделать эти поля не опциональными
Тогда вью модель будет полностью отвечать за контент этого экрана, и если тебе нужно будет сменить плейсхолдеры, то ты не будешь бегать по всем файлам и искать ??, а просто заменишь все во вью модели

и функцию logoImageSetting тоже вызывать только в ProfileCellsData, сделать ее статической и приватной
 
ps: мы все ближе к богу

2023-04-30 10:09 UTC, vaganova-ann approved these changes

2023-04-30 13:35 UTC, merged